/*
 * This source file was generated by the Gradle 'init' task
 */
package project;

// import org.junit.jupiter.api.Test;

import compiler.App;
import compiler.Lexer.CompilerLexer;
import compiler.Lexer.Tokens.Token;

import java.io.IOException;
import java.io.PushbackReader;
import java.io.StringReader;
import java.util.LinkedList;
import java.util.List;
import java.util.NoSuchElementException;

class AppTest {
    @org.junit.Test void appHasAGreeting() throws IOException, Exception {
         StringReader sourceCode = new StringReader("def Point copyPoints(Point[] p) { \r\n" + //
                        "    return Point(p[0].x+p[1].x, p[0].y+p[1].y); \r\n" + //
                        "}");

        PushbackReader reader = new PushbackReader(sourceCode, 1);

        CompilerLexer lexer = new CompilerLexer(reader);

        List<Token> tokens = new LinkedList<>();
        try {
            Token currToken = lexer.nextToken();
            while(true) {
                tokens.addLast(currToken);
                currToken = lexer.nextToken();
            }
        } catch (NoSuchElementException e) {
            // TODO: handle exception
    //     }
    // assertEquals(41, tokens.size(), "Token count mismatch");

    // assertEquals("Keyword", tokens.get(0).getClass().getSimpleName());        // def
    // assertEquals("Identifier", tokens.get(1).getClass().getSimpleName());     // Point
    // assertEquals("Identifier", tokens.get(2).getClass().getSimpleName());     // copyPoints
    // assertEquals("Brackets", tokens.get(3).getClass().getSimpleName());       // (
    // assertEquals("Identifier", tokens.get(4).getClass().getSimpleName());     // Point
    // assertEquals("Brackets", tokens.get(5).getClass().getSimpleName());       // [
    // assertEquals("Brackets", tokens.get(6).getClass().getSimpleName());       // ]
    // assertEquals("Identifier", tokens.get(7).getClass().getSimpleName());     // p
    // assertEquals("Brackets", tokens.get(8).getClass().getSimpleName());       // )
    // assertEquals("Brackets", tokens.get(9).getClass().getSimpleName());       // {
    
    // assertEquals("Keyword", tokens.get(10).getClass().getSimpleName());       // return
    // assertEquals("Identifier", tokens.get(11).getClass().getSimpleName());    // Point
    // assertEquals("Brackets", tokens.get(12).getClass().getSimpleName());      // (
    // assertEquals("Identifier", tokens.get(13).getClass().getSimpleName());     // p
    // assertEquals("Brackets", tokens.get(14).getClass().getSimpleName());      // [
    // assertEquals("NumberToken", tokens.get(15).getClass().getSimpleName());   // 0
    // assertEquals("Brackets", tokens.get(16).getClass().getSimpleName());      // ]
    // assertEquals("ObjectAccessor", tokens.get(17).getClass().getSimpleName());// .
    // assertEquals("Identifier", tokens.get(18).getClass().getSimpleName());    // x
    // assertEquals("Operator", tokens.get(19).getClass().getSimpleName());      // +
    
    // assertEquals("Brackets", tokens.get(20).getClass().getSimpleName());      // [
    // assertEquals("NumberToken", tokens.get(21).getClass().getSimpleName());   // 1
    // assertEquals("Brackets", tokens.get(22).getClass().getSimpleName());      // ]
    // assertEquals("ObjectAccessor", tokens.get(23).getClass().getSimpleName());// .
    // assertEquals("Identifier", tokens.get(24).getClass().getSimpleName());    // x
    // assertEquals("Seperator", tokens.get(25).getClass().getSimpleName());     // ,
    
    // assertEquals("Identifier", tokens.get(26).getClass().getSimpleName());    // p
    // assertEquals("Brackets", tokens.get(27).getClass().getSimpleName());      // [
    // assertEquals("NumberToken", tokens.get(28).getClass().getSimpleName());   // 0
    // assertEquals("Brackets", tokens.get(29).getClass().getSimpleName());      // ]
    // assertEquals("ObjectAccessor", tokens.get(30).getClass().getSimpleName());// .
    // assertEquals("Identifier", tokens.get(31).getClass().getSimpleName());    // y
    // assertEquals("Operator", tokens.get(32).getClass().getSimpleName());      // +
    // assertEquals("Brackets", tokens.get(33).getClass().getSimpleName());      // [
    // assertEquals("NumberToken", tokens.get(34).getClass().getSimpleName());   // 1
    // assertEquals("Brackets", tokens.get(35).getClass().getSimpleName());      // ]
    // assertEquals("ObjectAccessor", tokens.get(36).getClass().getSimpleName());// .
    // assertEquals("Identifier", tokens.get(37).getClass().getSimpleName());    // y
    // assertEquals("Brackets", tokens.get(38).getClass().getSimpleName());      // )
    // assertEquals("Seperator", tokens.get(39).getClass().getSimpleName());     // ;
    
    // assertEquals("Brackets", tokens.get(40).getClass().getSimpleName());
    }
}
}