/*
 * This source file was generated by the Gradle 'init' task
 */
package compiler;
/*

"{\n" +
        "    \"version\": 17,\n" +
        "    \"bundles\": [\n" +
        "        { \"name\" : \"org.graalvm.component.installer.Bundle\" },\n" +
        "        { \"name\" : \"org.graalvm.component.installer.commands.Bundle\" },\n" +
        "        { \"name\" : \"org.graalvm.component.installer.remote.Bundle\" },\n" +
        "        { \"name\" : \"org.graalvm.component.installer.os.Bundle\" }\n" +
        "    ]\n" +
"}";

(EXTENDED BNF form) ->
  <Value> ::= <Object> | <String> | <Number> | <Array> | <Character>
  <Character> ::= ALL ASCII CHARACTERS
  <String> ::= "" | <Character> <String>
  <ArrayItems> ::= <Value> | <Value> "," <ArrayItems>
  <Array> ::= "[" <ArrayItems> "]"   
  <ObjectItem> ::= <String>":"<Value>
  <ObjectItems> ::= "" | <ObjectItem> "," <ObjectItems>
  <Object> ::= "{" <ObjectItems> "}"
*/

import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.PushbackReader;
import java.util.List;
import java.util.Map;

import compiler.DataStructures.EvaluationContext;
import compiler.DataStructures.SymbolTable;
import compiler.Lexer.CompilerLexer;
import compiler.Lexer.Tokens.Identifier;
import compiler.Parser.Exceptions.ArgumentError;
import compiler.Parser.Expressions.IdentifierExpression;
import compiler.Parser.Parsers.ProgramParser;
import compiler.Parser.Position;
import compiler.Parser.Statements.IdentifierType;
import compiler.Parser.Statements.Program;


class ArgsData 
{ 
    String filePath, outputDirectory, runningMode;

    ArgsData(String filePath, String runningMode, String outputDirectory) 
    {
        this.filePath = filePath;
        this.outputDirectory = outputDirectory;
        this.runningMode = runningMode;
    };
};

public class App {
    public String getGreeting() {
        return "Hello Mohanned!";
    }

    public static SymbolTable initializeSymbolTable() 
    {
        SymbolTable table = new SymbolTable(null);

        Map<String, List<IdentifierType>> argsMap = Constants.getBuiltInMethodsArgumentMapping();
        Map<String, IdentifierType> returnMap = Constants.getReturnTypeMapping();

        for (String methodName : argsMap.keySet()) 
        {
            List<IdentifierType> expectedArguments = argsMap.get(methodName);
            IdentifierType expectedReturnType = returnMap.get(methodName);

            Identifier methodIdentifier = new Identifier(methodName);
            IdentifierExpression methodIdExpr = new IdentifierExpression(methodIdentifier);
            table.insert(methodIdExpr, expectedReturnType, false);
            table.insertMethod(methodIdExpr, expectedArguments);
        }

        return table;
    };


    public static ArgsData parseArgs(String[] args) throws ArgumentError
    {
        String runningMode = null, filePath = null, outputDirectory = null;
        if(args.length == 0) 
        {
            throw new ArgumentError(String.format("Expected a file path to compile the code as an argument."));
        }

        filePath = args[0];

        int currIdx = 1;

        while(currIdx < args.length) {
            String argument = args[currIdx];

            if(Utils.checkExists(new String[] {"-lexer", "-parser", "analysis", "-code-generation"}, argument)) {
                if(runningMode != null) {
                    throw new ArgumentError(String.format("It seems like you have provided two running modes. %s and %s", argument, runningMode));
                }
                runningMode = argument;
            } else {
                if(!argument.equals("-o")) 
                {
                    throw new ArgumentError(String.format("Invalid argument. Got %s", argument));
                }
                currIdx += 1; // increase the pointer to get the outputFile. 
                if(currIdx >= args.length) 
                {
                    throw new ArgumentError("Expected an output directory for the compiled code");
                }
                outputDirectory = args[currIdx];
            }
            currIdx += 1;
        }

        if(outputDirectory == null) outputDirectory = "currBuild";

        return new ArgsData(filePath, runningMode, outputDirectory);
    };

    public static void main(String[] args) throws IOException, Exception {
        ArgsData argsData = App.parseArgs(args);

        // StringReader reader = new StringReader(code);
        FileReader fileReader = null;
        EvaluationContext context = new EvaluationContext();
        try {
            fileReader = new FileReader(argsData.filePath); 
            CompilerLexer lexer = new CompilerLexer(new PushbackReader(fileReader));

            ProgramParser programParser = new ProgramParser(lexer, new Position());

            Program programNode = programParser.parse();

            SymbolTable table = initializeSymbolTable();

            programNode.analyze(table);

            programNode.emit(context);


            String outputDirectory = argsData.outputDirectory;

            File outFile = new File(outputDirectory);
            File parentFile = outFile.getParentFile();
            
            if (!parentFile.exists()) 
            {
                parentFile.mkdirs();
            }
            
            for(String className : context.compiledClasses.keySet()) 
            {
                outFile = new File(parentFile + "/" + className + ".class");
                byte[] compiledByteCode = context.compiledClasses.get(className);
                try(FileOutputStream fos = new FileOutputStream(outFile)) {
                    fos.write(compiledByteCode);
                }
            }
        } catch (Exception e) {
            throw e;
        } finally {
            if(fileReader != null) {
                fileReader.close();
            }
        }
    }
}


/* 
"
(EXTENDED BNF form) ->
    <BLOCK_SCOPE> ::= '{' <EXPRESSIONS // will figure this out later!
    Expressions Definition ->     
        <METHOD_INVOCATION_EXPRESSION> ::= <IDENTIFIER>'('<METHOD_INVOCATION_PARAMS>')'
        <METHOD_INVOCATION_PARAMS> ::= <EXPRESSION> | <EXPRESSION> ',' <METHOD_INVOCATION_PARAMS> | <EPSILON>
        <NUMERIC_TERM> ::= <METHOD_INVOCATION_EXPRESSION> | <IDENTIFIER> | <NUMBER>
        <ARITHMETIC_EXPRESSION> ::= <NUMERIC_TERM> <ARITHMATIC_OPERATOR> <ARITHMETIC_EXPRESSION> | <ARITHMETIC_EXPRESSION> <ARITHMATIC_OPERATOR> <ARITHMETIC_EXPRESSION> | <ARITHMETIC_EXPRESSION> | '(' <ARITHMETIC_EXPRESSION> ')' 
        <BOOLEAN_EXPRESSION> ::= <EXPRESSION> <BOOLEAN_OPERATOR> <EXPRESSION> | <EXPRESSION>
        <RANGE_EXPRESSION> ::= <ARITHMETIC_EXPRESSION> <RANGE_OPERATOR>
        <INDEXING_EXPRESSION> ::= <IDENTIFIER> '[' <ARITHMETIC_EXPRESSION> ']'
        <IDENTIFIER_FIELD_ACCESSOR_EXPRESSION> ::= <EXPRESSION> '.' <IDENTIFIER_FIELD_ACCESSOR_EXPRESSION> | <IDENTIFIER>
        <FIELD_ACCESSOR_EXPRESSION> ::= (<IDENTIFIER> | <METHOD_INVOCATION_EXPRESSION>) '.' <IDENTIFIER_FIELD_ACCESSOR_EXPRESSION>
        <EXPRESSION> ::= <BOOLEAN_EXPRESSION> | <ARITHMETIC_EXPRESSION> | <METHOD_INVOCATION_EXPRESSION> | <FIELD_ACCESSOR_EXPRESSION> | <IDENTIFIER> | <STRING> | <NUMBER> | <BOOL> | '(' <EXPRESSION> ')'
            
    Statements Definition -> 
        <VARIABLE_ASSIGNMENT_STATEMENT> ::= <VARIABLE_DECLARATION> '=' <EXPRESSION>
        <VARIABLE_DECLARATION> ::= <TYPE> <IDENTIFIER>
        <CONST_ASSIGNMENT_STATEMENT> ::= final <VARIABLE_ASSIGNMENT_EXPRESSION>

    Struct Definition ->
        <STRUCT_DEFINITION> ::= coll <IDENTIFIER> '{' <STRUCT_PROPERTIES> '}'
        <STRUCT_PROPERTY> ::= <TYPE> <IDENTIFIER> ';'
        <STRUCT_PROPERTIES> ::= <STRUCT_PROPERTY> <STRUCT_PROPERTIES> | <EPSILON>

    <BLOCK_SCOPE> ::= '{' <STATEMENT_LIST> '}'

    Methods Definition ->
        <METHOD_PARAMS> ::= <METHOD_PARAM> ',' <METHOD_PARAMS> | <METHOD_PARAM>
        <METHOD_DEFINITION> ::= def <IDENTIFIER> '(' <METHOD_PARAMS> ')' <BLOCK_SCOPE>

    Loops ->
        <WHILE_LOOP> ::= 'while' '(' <EXPRESSION> ')'
*/
