/*
 * This source file was generated by the Gradle 'init' task
 */
package project;


/*

"{\n" +
        "    \"version\": 17,\n" +
        "    \"bundles\": [\n" +
        "        { \"name\" : \"org.graalvm.component.installer.Bundle\" },\n" +
        "        { \"name\" : \"org.graalvm.component.installer.commands.Bundle\" },\n" +
        "        { \"name\" : \"org.graalvm.component.installer.remote.Bundle\" },\n" +
        "        { \"name\" : \"org.graalvm.component.installer.os.Bundle\" }\n" +
        "    ]\n" +
"}";

(EXTENDED BNF form) ->
  <Value> ::= <Object> | <String> | <Number> | <Array> | <Character>
  <Character> ::= ALL ASCII CHARACTERS
  <String> ::= "" | <Character> <String>
  <ArrayItems> ::= <Value> | <Value> "," <ArrayItems>
  <Array> ::= "[" <ArrayItems> "]"   
  <ObjectItem> ::= <String>":"<Value>
  <ObjectItems> ::= "" | <ObjectItem> "," <ObjectItems>
  <Object> ::= "{" <ObjectItems> "}"
*/


class Parser {
    public String input_string;
    public int curr_index;

    Parser(String input_string) {
        this.input_string = new String(input_string);
        this.curr_index = 0;
    };

    boolean parse_object() {
        return false;
    };

    boolean parse_main() {
        return false;
    };

    boolean parse_string() {
        while(input_string.charAt(curr_index) != '\"') {
            
        };
        return false;  
    };

    boolean parse_value() {
        return false;
    }

    boolean parse_object_item() {
        String object_key = "", object_value = "";        
        while(input_string.charAt(curr_index) != ':') {
            object_key += input_string.charAt(curr_index);
            curr_index += 1;
        };
        return false;   
    };
};

public class App {
    private static final String EXAMPLE_INPUT = "{\n" +
        "    \"version\": 17,\n" +
        "    \"bundles\": [\n" +
        "        { \"name\" : \"org.graalvm.component.installer.Bundle\" },\n" +
        "        { \"name\" : \"org.graalvm.component.installer.commands.Bundle\" },\n" +
        "        { \"name\" : \"org.graalvm.component.installer.remote.Bundle\" },\n" +
        "        { \"name\" : \"org.graalvm.component.installer.os.Bundle\" }\n" +
        "    ]\n" +
        "}";

    public String getGreeting() {
        return "Hello Mohanned!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}


