/*
 * This source file was generated by the Gradle 'init' task
 */
package compiler;
/*

"{\n" +
        "    \"version\": 17,\n" +
        "    \"bundles\": [\n" +
        "        { \"name\" : \"org.graalvm.component.installer.Bundle\" },\n" +
        "        { \"name\" : \"org.graalvm.component.installer.commands.Bundle\" },\n" +
        "        { \"name\" : \"org.graalvm.component.installer.remote.Bundle\" },\n" +
        "        { \"name\" : \"org.graalvm.component.installer.os.Bundle\" }\n" +
        "    ]\n" +
"}";

(EXTENDED BNF form) ->
  <Value> ::= <Object> | <String> | <Number> | <Array> | <Character>
  <Character> ::= ALL ASCII CHARACTERS
  <String> ::= "" | <Character> <String>
  <ArrayItems> ::= <Value> | <Value> "," <ArrayItems>
  <Array> ::= "[" <ArrayItems> "]"   
  <ObjectItem> ::= <String>":"<Value>
  <ObjectItems> ::= "" | <ObjectItem> "," <ObjectItems>
  <Object> ::= "{" <ObjectItems> "}"
*/

import java.io.IOException;
import java.io.PushbackReader;
import java.io.StringReader;
import java.util.LinkedList;
import java.util.NoSuchElementException;

import compiler.Lexer.CompilerLexer;
import compiler.Lexer.Tokens.Token;

public class App {
    private static final String EXAMPLE_INPUT = "{\n" +
        "    \"version\": 17,\n" +
        "    \"bundles\": [\n" +
        "        { \"name\" : \"org.graalvm.component.installer.Bundle\" },\n" +
        "        { \"name\" : \"org.graalvm.component.installer.commands.Bundle\" },\n" +
        "        { \"name\" : \"org.graalvm.component.installer.remote.Bundle\" },\n" +
        "        { \"name\" : \"org.graalvm.component.installer.os.Bundle\" }\n" +
        "    ]\n" +
        "}";

    public String getGreeting() {
        return "Hello Mohanned!";
    }

    public static void main(String[] args) throws IOException, Exception {
        StringReader sourceCode = new StringReader("def Point copyPoints(Point[] p) { \r\n" + //
                        "    return Point(p[0].x+p[1].x, p[0].y+p[1].y); \r\n" + //
                        "}");

        PushbackReader reader = new PushbackReader(sourceCode, 1);

        CompilerLexer lexer = new CompilerLexer(reader);

        LinkedList<Token> tokens = new LinkedList<>();
        try {
            Token currToken = lexer.nextToken();
            while(true) {
                tokens.addLast(currToken);
                currToken = lexer.nextToken();
            }
        } catch (NoSuchElementException e) {
            // TODO: handle exception
        }

        System.out.println(tokens);
    }
}


